export default {
    resourceslist: [
        {
            enclosureFormat: '05',
            ownerCompany: 10003,
            resourceEnableStatus: '1',
            enclosureStateName: '转换成功',
            enclosureTag: '',
            addToCourse: 1,
            creatorId: 5735,
            creatorName: 'yy',
            courseCategory: 432,
            enclosureLength: '00:45:19',
            courseCategoryName: 'yuan_3',
            modifyTime: '2020-08-25 17:30:00',
            modifyName: 'yy',
            modifyLoginName: 'testyyy',
            id: 3079,
            enclosureState: '1',
            creatorLoginName: 'testyyy',
            enclosureName: '流星花园2 - 副本.mp4',
            modifyId: 5735,
            enclosureSize: '170.52M',
            createTime: '2020-08-25 17:17:20',
            aliCloud: '173b2ec76c8544d8948cd47bfcf8bf39',
            courseCategoryLevelPath: '429.430.431.432',
            multimediaMillisecond: 2719000,
            resourceTagNames: '',
        },
        {
            enclosureFormat: '05',
            ownerCompany: 10003,
            resourceEnableStatus: '1',
            enclosureStateName: '转换成功',
            enclosureTag: '',
            addToCourse: 0,
            creatorId: 5771,
            creatorName: 'liulu',
            courseCategory: 396,
            enclosureLength: '00:00:10',
            courseCategoryName: '入列引导篇',
            modifyTime: '2020-08-12 17:30:01',
            modifyName: 'liulu',
            modifyLoginName: 'qxzxliulu',
            id: 3078,
            enclosureState: '1',
            creatorLoginName: 'qxzxliulu',
            enclosureName: '短视频.mp4',
            modifyId: 5771,
            enclosureSize: '2.47M',
            createTime: '2020-08-12 17:17:18',
            aliCloud: 'b472dfdc55f04050b2f3c1cd2edff201',
            courseCategoryLevelPath: '393.396',
            multimediaMillisecond: 10000,
            resourceTagNames: '',
        },
        {
            enclosureFormat: '05',
            ownerCompany: 10003,
            resourceEnableStatus: '1',
            enclosureStateName: '转换成功',
            enclosureTag: '',
            addToCourse: 1,
            creatorId: 1117,
            creatorName: 'ADMIN10003',
            courseCategory: 503,
            enclosureLength: '00:01:05',
            courseCategoryName: '四级类A102',
            modifyTime: '2020-07-28 15:45:01',
            modifyName: 'ADMIN10003',
            modifyLoginName: 'admin10003',
            id: 3075,
            enclosureState: '1',
            creatorLoginName: 'admin10003',
            enclosureName: '测试仲CCC.mp4',
            modifyId: 1117,
            enclosureSize: '6.34M',
            createTime: '2020-07-28 15:38:46',
            aliCloud: '756faf4f18534c29b7543a6c188932f3',
            courseCategoryLevelPath: '497.498.499.503',
            multimediaMillisecond: 65000,
            resourceTagNames: '',
        },
        {
            enclosureFormat: '05',
            ownerCompany: 10003,
            resourceEnableStatus: '1',
            enclosureStateName: '转换成功',
            enclosureTag: '',
            addToCourse: 0,
            creatorId: 1117,
            creatorName: 'ADMIN10003',
            courseCategory: 503,
            enclosureLength: '00:02:04',
            courseCategoryName: '四级类A102',
            modifyTime: '2020-07-28 15:45:01',
            modifyName: 'ADMIN10003',
            modifyLoginName: 'admin10003',
            id: 3076,
            enclosureState: '1',
            creatorLoginName: 'admin10003',
            enclosureName: '测试仲DDD.mp4',
            modifyId: 1117,
            enclosureSize: '8.84M',
            createTime: '2020-07-28 15:38:46',
            aliCloud: 'ff9e2359df834fcd89d76aea2db8f39c',
            courseCategoryLevelPath: '497.498.499.503',
            multimediaMillisecond: 124000,
            resourceTagNames: '',
        },
        {
            enclosureFormat: '05',
            ownerCompany: 10003,
            resourceEnableStatus: '1',
            enclosureStateName: '转换成功',
            enclosureTag: '',
            addToCourse: 1,
            creatorId: 5730,
            creatorName: '哈哈哈',
            courseCategory: 501,
            enclosureLength: '00:02:04',
            courseCategoryName: '二级类B',
            modifyTime: '2020-06-23 15:15:00',
            modifyName: '哈哈哈',
            modifyLoginName: 'zzd564',
            id: 3064,
            enclosureState: '1',
            creatorLoginName: 'zzd564',
            enclosureName: '测试仲555.mp4',
            modifyId: 5730,
            enclosureSize: '8.84M',
            createTime: '2020-06-23 15:14:13',
            aliCloud: '3195ea20520d4e65abe6cff8464bcfb1',
            courseCategoryLevelPath: '497.501',
            multimediaMillisecond: 124000,
            resourceTagNames: '',
        },
    ],
    ontheleftlist: [
        {
            title: 'parent 1',
            expand: true,
            children: [
                {
                    title: 'parent 1-1',
                    expand: true,
                    children: [
                        {
                            title: 'leaf 1-1-1',
                        },
                        {
                            title: 'leaf 1-1-2',
                        },
                    ],
                },
                {
                    title: 'parent 1-2',
                    expand: true,
                    children: [
                        {
                            title: 'leaf 1-2-1',
                        },
                        {
                            title: 'leaf 1-2-1',
                        },
                    ],
                },
            ],
        },
    ],
    classificationlist: [
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 4189,
            creatorId: 5573,
            creatorName: '徐倩玉',
            categoryPictureLocked: '',
            sort: null,
            title: '新兵必修课程',
            orgId: 221,
            parentId: 0,
            modifyTime: '2020-02-19 07:08:40',
            modifyName: 'manager',
            createTime: '2020-02-17 21:07:03',
            courseCategoryLevelPath: '393',
            categoryState: '1',
            id: 393,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 4189,
            creatorId: 5572,
            creatorName: '张旭',
            categoryPictureLocked: '',
            sort: null,
            title: '老兵晋级课程',
            orgId: 221,
            parentId: 0,
            modifyTime: '2020-02-19 07:10:22',
            modifyName: 'manager',
            createTime: '2020-02-17 21:15:07',
            courseCategoryLevelPath: '395',
            categoryState: '1',
            id: 395,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 4186,
            creatorId: 4186,
            creatorName: '卢宗洋',
            categoryPictureLocked: '',
            sort: null,
            title: '新型冠状病毒相关',
            orgId: 221,
            parentId: 0,
            modifyTime: '2020-02-26 12:59:56',
            modifyName: '卢宗洋',
            createTime: '2020-02-26 12:20:13',
            courseCategoryLevelPath: '423',
            categoryState: '1',
            id: 423,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5735,
            creatorId: 5735,
            creatorName: 'yy',
            categoryPictureLocked: '',
            sort: null,
            title: 'yuan',
            orgId: 407,
            parentId: 0,
            modifyTime: '2020-04-29 17:19:18',
            modifyName: 'yy',
            createTime: '2020-04-29 17:19:18',
            courseCategoryLevelPath: '429',
            categoryState: '1',
            id: 429,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5746,
            creatorId: 5746,
            creatorName: '刘淼',
            categoryPictureLocked: '',
            sort: null,
            title: '大刘嘚吧嘚',
            orgId: 407,
            parentId: 0,
            modifyTime: '2020-04-30 11:19:30',
            modifyName: '刘淼',
            createTime: '2020-04-29 17:51:55',
            courseCategoryLevelPath: '434',
            categoryState: '1',
            id: 434,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 1117,
            creatorId: 1117,
            creatorName: 'ADMIN10003',
            categoryPictureLocked: '',
            sort: null,
            title: 'zzd',
            orgId: 1,
            parentId: 0,
            modifyTime: '2020-04-30 16:56:35',
            modifyName: 'ADMIN10003',
            createTime: '2020-04-30 16:56:35',
            courseCategoryLevelPath: '456',
            categoryState: '1',
            id: 456,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5730,
            creatorId: 5730,
            creatorName: '哈哈哈',
            categoryPictureLocked: '',
            sort: null,
            title: '类BCDE',
            orgId: 399,
            parentId: 0,
            modifyTime: '2020-05-07 17:56:52',
            modifyName: '哈哈哈',
            createTime: '2020-05-07 17:56:52',
            courseCategoryLevelPath: '468',
            categoryState: '1',
            id: 468,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5730,
            creatorId: 5730,
            creatorName: '哈哈哈',
            categoryPictureLocked: '',
            sort: null,
            title: '怪怪的',
            orgId: 399,
            parentId: 0,
            modifyTime: '2020-05-07 17:59:03',
            modifyName: '哈哈哈',
            createTime: '2020-05-07 17:59:03',
            courseCategoryLevelPath: '472',
            categoryState: '1',
            id: 472,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5730,
            creatorId: 5730,
            creatorName: '哈哈哈',
            categoryPictureLocked: '',
            sort: null,
            title: '来来来',
            orgId: 399,
            parentId: 0,
            modifyTime: '2020-05-07 18:00:44',
            modifyName: '哈哈哈',
            createTime: '2020-05-07 18:00:44',
            courseCategoryLevelPath: '476',
            categoryState: '1',
            id: 476,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5735,
            creatorId: 5735,
            creatorName: 'yy',
            categoryPictureLocked: '',
            sort: null,
            title: '热恩',
            orgId: 407,
            parentId: 0,
            modifyTime: '2020-05-07 18:04:41',
            modifyName: 'yy',
            createTime: '2020-05-07 18:04:41',
            courseCategoryLevelPath: '480',
            categoryState: '1',
            id: 480,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5730,
            creatorId: 5730,
            creatorName: '哈哈哈',
            categoryPictureLocked: '',
            sort: null,
            title: '嘿嘿嘿',
            orgId: 399,
            parentId: 0,
            modifyTime: '2020-05-07 18:05:47',
            modifyName: '哈哈哈',
            createTime: '2020-05-07 18:05:47',
            courseCategoryLevelPath: '484',
            categoryState: '1',
            id: 484,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5730,
            creatorId: 5730,
            creatorName: '哈哈哈',
            categoryPictureLocked: '',
            sort: null,
            title: '咕咕咕咕',
            orgId: 399,
            parentId: 0,
            modifyTime: '2020-05-07 18:06:59',
            modifyName: '哈哈哈',
            createTime: '2020-05-07 18:06:59',
            courseCategoryLevelPath: '487',
            categoryState: '1',
            id: 487,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5749,
            creatorId: 5749,
            creatorName: 'qxzmn003',
            categoryPictureLocked: '',
            sort: null,
            title: '方式',
            orgId: 407,
            parentId: 0,
            modifyTime: '2020-05-07 18:07:58',
            modifyName: 'qxzmn003',
            createTime: '2020-05-07 18:07:58',
            courseCategoryLevelPath: '488',
            categoryState: '1',
            id: 488,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5730,
            creatorId: 5730,
            creatorName: '哈哈哈',
            categoryPictureLocked: '',
            sort: null,
            title: '哈哈哈哈',
            orgId: 399,
            parentId: 0,
            modifyTime: '2020-05-07 18:32:17',
            modifyName: '哈哈哈',
            createTime: '2020-05-07 18:32:17',
            courseCategoryLevelPath: '493',
            categoryState: '1',
            id: 493,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5730,
            creatorId: 5730,
            creatorName: '哈哈哈',
            categoryPictureLocked: '',
            sort: null,
            title: '类zzd',
            orgId: 399,
            parentId: 0,
            modifyTime: '2020-05-26 15:59:06',
            modifyName: '哈哈哈',
            createTime: '2020-05-26 15:59:06',
            courseCategoryLevelPath: '497',
            categoryState: '1',
            id: 497,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5735,
            creatorId: 5735,
            creatorName: 'yy',
            categoryPictureLocked: '',
            sort: null,
            title: '课程一级',
            orgId: 413,
            parentId: 0,
            modifyTime: '2020-06-18 17:33:36',
            modifyName: 'yy',
            createTime: '2020-06-18 17:33:36',
            courseCategoryLevelPath: '506',
            categoryState: '1',
            id: 506,
        },
        {
            ownerCompany: 10003,
            categoryPicture: '',
            level: 1,
            modifyId: 5735,
            creatorId: 5735,
            creatorName: 'yy',
            categoryPictureLocked: '',
            sort: null,
            title: '111',
            orgId: 413,
            parentId: 0,
            modifyTime: '2020-08-17 15:48:11',
            modifyName: 'yy',
            createTime: '2020-08-17 15:48:11',
            courseCategoryLevelPath: '515',
            categoryState: '1',
            id: 515,
        },
    ],
};
